name: Assignment3

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.yaml'
      - '**.txt'

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_HOST_AUTH_METHOD: trust  # Allow all connections without a password
      
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt


      - name: Run application
        run: |
          python3 Application.py &

      - name: Wait for application to start
        run: sleep 10

      - name: Run integration tests
        run: |
          python3 Integration_Test.py
