name: Packer CI/CD

on:
  pull_request:
    branches:
      - main
    paths:
      - '*.pkr.hcl'

jobs:
  packer_status_check:
    runs-on: ubuntu-latest
    steps:
      

      - name: Check for .pkr.hcl files and format
        run: |
          # Check if .pkr.hcl files exist
          if [ -n "$(find . -name '*.pkr.hcl' -print -quit)" ]; then
            echo ".pkr.hcl files found, running packer fmt..."
            if packer fmt -check -write=false .; then
              echo "Packer templates are properly formatted."
            else
              echo "Packer templates need formatting. Please format the templates using 'packer fmt' and push the changes."
              exit 1
            fi
          else
            echo "No .pkr.hcl files found, skipping packer fmt check."
            exit 0
          fi

  build_custom_image:
    runs-on: ubuntu-latest
    needs: packer_status_check
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: '3.13.0-alpha.4'

      - name: Install dependencies
        run: |
          pip install --upgrade pip setuptools wheel
      
      - name: Build distribution package
        run: python3 setup.py sdist bdist_wheel
      
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.SA_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'


      - name: Run packer validate
        run: |
          # Check if .pkr.hcl files exist
          if [ -n "$(find . -name '*.pkr.hcl' -print -quit)" ]; then
            echo ".pkr.hcl files found, running packer fmt..."
            packer init Packer.pkr.hcl
            packer validate Packer.pkr.hcl
            packer build Packer.pkr.hcl
          else
            echo "No .pkr.hcl files found, skipping packer fmt check."
            exit 0
          fi
