name: Packer CI/CD

on:
  pull_request:
    branches:
      - main
    paths:
      - '*.pkr.hcl'

jobs:
  packer_status_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for .pkr.hcl files and format
        run: |
          # Check if .pkr.hcl files exist
          if [ -n "$(find . -name '*.pkr.hcl' -print -quit)" ]; then
            echo ".pkr.hcl files found, running packer fmt..."
            if packer fmt -check -write=false .; then
              echo "Packer templates are properly formatted."
            else
              echo "Packer templates need formatting. Please format the templates using 'packer fmt' and push the changes."
              exit 1
            fi
          else
            echo "No .pkr.hcl files found, skipping packer fmt check."
            exit 0
          fi

  build_custom_image:
    runs-on: ubuntu-latest
    needs: packer_status_check

    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Debug SA_KEY
        run: echo "SA_KEY:${{ secrets.SA_KEY }}"

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          service_account_email: ${{ secrets.SA_EMAIL }}
          service_account_key: ${{ secrets.SA_KEY }}
          
      - name: Authenticate with Google Cloud SDK
        run: gcloud auth activate-service-account --key-file=service_account_key
         
          

      - name: Build application artifact
        run: |
          python setup.py sdist --format=gztar

      - name: Run packer validate
        run: |
          # Check if .pkr.hcl files exist
          if [ -n "$(find . -name '*.pkr.hcl' -print -quit)" ]; then
            echo ".pkr.hcl files found, running packer fmt..."
            packer init Packer.pkr.hcl
            packer validate Packer.pkr.hcl
            packer build Packer.pkr.hcl
          else
            echo "No .pkr.hcl files found, skipping packer fmt check."
            exit 0
          fi
