name: Packer CI/CD

on:
  pull_request:
    branches:
      - main
    paths:
      - '*.pkr.hcl'

jobs:
  packer_status_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for .pkr.hcl files and format
        run: |
          # Check if .pkr.hcl files exist
          if [ -n "$(find . -name '*.pkr.hcl' -print -quit)" ]; then
            echo ".pkr.hcl files found, running packer fmt..."
            if packer fmt -check -write=false .; then
              echo "Packer templates are properly formatted."
            else
              echo "Packer templates need formatting. Please format the templates using 'packer fmt' and push the changes."
              exit 1
            fi
          else
            echo "No .pkr.hcl files found, skipping packer fmt check."
            exit 0
          fi
      - name: Install packer plugin
        run: |
          packer init -plugins=packer-builder-googlecompute
      - name: Run packer validate
        run: |
          # Check if .pkr.hcl files exist
          if [ -n "$(find . -name '*.pkr.hcl' -print -quit)" ]; then
            echo ".pkr.hcl files found, running packer fmt..."
            packer validate Packer.pkr.hcl
          else
            echo "No .pkr.hcl files found, skipping packer fmt check."
            exit0
          fi

  build_custom_image:
    runs-on: ubuntu-latest
    needs: packer_status_check
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true && contains(github.event.pull_request.head.repo.default_branch, '.pkr.hcl')
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.4.0
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          service_account_key: ${{ secrets.SA_KEY }}
          export_default_credentials: true

      - name: Build application artifact
        run: |
          python setup.py sdist --format=gztar

      - name: Build custom image
        run: |
          # Check if .pkr.hcl files exist
          if [ -n "$(find . -name '*.pkr.hcl' -print -quit)" ]; then
            echo ".pkr.hcl files found, building custom image..."
            packer init Packer.pkr.hcl
            packer build Packer.pkr.hcl
          else
            echo "No .pkr.hcl files found, skipping build custom image step."
          fi
